apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: app-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: mickybamby/app-python:v1.0
        ports:
        - port: 8000
          targetPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"