apiVersion: v1
kind: Service
metadata:
  name: mike-python-service
  namespace: default
spec:
  selector:
    app: app-python  # must match deployment labels
  ports:
    - protocol: TCP
      port: 8000         # this is the port clients connect to
      targetPort: 8000    # this must match your pod containerPort
  type: ClusterIP