apiVersion: v1
kind: Service
metadata:
  name: mike-python-service
spec:
  selector:
    app: app-python # Ensure this matches the labels in your deployment.yaml
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000  # Adjust to match the container port in deployment.yaml
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed