apiVersion: v1
kind: Service
metadata:
  name: mike-python-service
spec:
  selector:
    app: mickybamby/app-python # Ensure this matches the labels in your deployment.yaml
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # Adjust to match the container port in deployment.yaml
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed